# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/BWRS1_dev/krump_vst

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/BWRS1_dev/krump_vst

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/BWRS1_dev/krump_vst/CMakeFiles /Users/BWRS1_dev/krump_vst//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/BWRS1_dev/krump_vst/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/BWRS1_dev/krump_vst/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NewProject

# Build rule for target.
NewProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewProject
.PHONY : NewProject

# fast build rule for target.
NewProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/build
.PHONY : NewProject/fast

#=============================================================================
# Target rules for targets named NewProject_All

# Build rule for target.
NewProject_All: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewProject_All
.PHONY : NewProject_All

# fast build rule for target.
NewProject_All/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_All.dir/build.make CMakeFiles/NewProject_All.dir/build
.PHONY : NewProject_All/fast

#=============================================================================
# Target rules for targets named NewProject_Standalone

# Build rule for target.
NewProject_Standalone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewProject_Standalone
.PHONY : NewProject_Standalone

# fast build rule for target.
NewProject_Standalone/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/build
.PHONY : NewProject_Standalone/fast

#=============================================================================
# Target rules for targets named NewProject_AU

# Build rule for target.
NewProject_AU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewProject_AU
.PHONY : NewProject_AU

# fast build rule for target.
NewProject_AU/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/build
.PHONY : NewProject_AU/fast

#=============================================================================
# Target rules for targets named NewProject_VST3

# Build rule for target.
NewProject_VST3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NewProject_VST3
.PHONY : NewProject_VST3

# fast build rule for target.
NewProject_VST3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/build
.PHONY : NewProject_VST3/fast

#=============================================================================
# Target rules for targets named juce_vst3_helper

# Build rule for target.
juce_vst3_helper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 juce_vst3_helper
.PHONY : juce_vst3_helper

# fast build rule for target.
juce_vst3_helper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/build
.PHONY : juce_vst3_helper/fast

#=============================================================================
# Target rules for targets named Resources

# Build rule for target.
Resources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Resources
.PHONY : Resources

# fast build rule for target.
Resources/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/build
.PHONY : Resources/fast

juce_binarydata_Resources/JuceLibraryCode/BinaryData1.o: juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData1.o

# target to build an object file
juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.o

juce_binarydata_Resources/JuceLibraryCode/BinaryData1.i: juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData1.i

# target to preprocess a source file
juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.i

juce_binarydata_Resources/JuceLibraryCode/BinaryData1.s: juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData1.s

# target to generate assembly for a file
juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData1.cpp.s

juce_binarydata_Resources/JuceLibraryCode/BinaryData2.o: juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData2.o

# target to build an object file
juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.o

juce_binarydata_Resources/JuceLibraryCode/BinaryData2.i: juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData2.i

# target to preprocess a source file
juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.i

juce_binarydata_Resources/JuceLibraryCode/BinaryData2.s: juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData2.s

# target to generate assembly for a file
juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData2.cpp.s

juce_binarydata_Resources/JuceLibraryCode/BinaryData3.o: juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData3.o

# target to build an object file
juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.o

juce_binarydata_Resources/JuceLibraryCode/BinaryData3.i: juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData3.i

# target to preprocess a source file
juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.i

juce_binarydata_Resources/JuceLibraryCode/BinaryData3.s: juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData3.s

# target to generate assembly for a file
juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData3.cpp.s

juce_binarydata_Resources/JuceLibraryCode/BinaryData4.o: juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData4.o

# target to build an object file
juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.o
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.o

juce_binarydata_Resources/JuceLibraryCode/BinaryData4.i: juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData4.i

# target to preprocess a source file
juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.i
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.i

juce_binarydata_Resources/JuceLibraryCode/BinaryData4.s: juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData4.s

# target to generate assembly for a file
juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Resources.dir/build.make CMakeFiles/Resources.dir/juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.s
.PHONY : juce_binarydata_Resources/JuceLibraryCode/BinaryData4.cpp.s

lib/JUCE/modules/juce_audio_basics/juce_audio_basics.o: lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : lib/JUCE/modules/juce_audio_basics/juce_audio_basics.o

# target to build an object file
lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.o

lib/JUCE/modules/juce_audio_basics/juce_audio_basics.i: lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : lib/JUCE/modules/juce_audio_basics/juce_audio_basics.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.i

lib/JUCE/modules/juce_audio_basics/juce_audio_basics.s: lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : lib/JUCE/modules/juce_audio_basics/juce_audio_basics.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : lib/JUCE/modules/juce_audio_basics/juce_audio_basics.mm.s

lib/JUCE/modules/juce_audio_devices/juce_audio_devices.o: lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : lib/JUCE/modules/juce_audio_devices/juce_audio_devices.o

# target to build an object file
lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.o

lib/JUCE/modules/juce_audio_devices/juce_audio_devices.i: lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : lib/JUCE/modules/juce_audio_devices/juce_audio_devices.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.i

lib/JUCE/modules/juce_audio_devices/juce_audio_devices.s: lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : lib/JUCE/modules/juce_audio_devices/juce_audio_devices.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : lib/JUCE/modules/juce_audio_devices/juce_audio_devices.mm.s

lib/JUCE/modules/juce_audio_formats/juce_audio_formats.o: lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : lib/JUCE/modules/juce_audio_formats/juce_audio_formats.o

# target to build an object file
lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.o

lib/JUCE/modules/juce_audio_formats/juce_audio_formats.i: lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : lib/JUCE/modules/juce_audio_formats/juce_audio_formats.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.i

lib/JUCE/modules/juce_audio_formats/juce_audio_formats.s: lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : lib/JUCE/modules/juce_audio_formats/juce_audio_formats.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : lib/JUCE/modules/juce_audio_formats/juce_audio_formats.mm.s

lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.o: lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.o

lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i: lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.i

lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s: lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/juce_vst3_helper.dir/build.make CMakeFiles/juce_vst3_helper.dir/lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.mm.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.mm.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.cpp.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.cpp.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.mm.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.mm.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.mm.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.cpp.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.mm.s

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o

# target to build an object file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.o
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.o

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.i
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.i

lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s: lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_Standalone.dir/build.make CMakeFiles/NewProject_Standalone.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_AU.dir/build.make CMakeFiles/NewProject_AU.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject_VST3.dir/build.make CMakeFiles/NewProject_VST3.dir/lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.s
.PHONY : lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.mm.s

lib/JUCE/modules/juce_audio_processors/juce_audio_processors.o: lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors.o

# target to build an object file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.o

lib/JUCE/modules/juce_audio_processors/juce_audio_processors.i: lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.i

lib/JUCE/modules/juce_audio_processors/juce_audio_processors.s: lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors.mm.s

lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.o: lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.o

# target to build an object file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o

lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i: lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i

lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s: lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s

lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o: lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o

# target to build an object file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o

lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i: lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i

lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s: lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s

lib/JUCE/modules/juce_audio_utils/juce_audio_utils.o: lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : lib/JUCE/modules/juce_audio_utils/juce_audio_utils.o

# target to build an object file
lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.o

lib/JUCE/modules/juce_audio_utils/juce_audio_utils.i: lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : lib/JUCE/modules/juce_audio_utils/juce_audio_utils.i

# target to preprocess a source file
lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.i

lib/JUCE/modules/juce_audio_utils/juce_audio_utils.s: lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : lib/JUCE/modules/juce_audio_utils/juce_audio_utils.s

# target to generate assembly for a file
lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : lib/JUCE/modules/juce_audio_utils/juce_audio_utils.mm.s

lib/JUCE/modules/juce_core/juce_core.o: lib/JUCE/modules/juce_core/juce_core.mm.o
.PHONY : lib/JUCE/modules/juce_core/juce_core.o

# target to build an object file
lib/JUCE/modules/juce_core/juce_core.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_core/juce_core.mm.o
.PHONY : lib/JUCE/modules/juce_core/juce_core.mm.o

lib/JUCE/modules/juce_core/juce_core.i: lib/JUCE/modules/juce_core/juce_core.mm.i
.PHONY : lib/JUCE/modules/juce_core/juce_core.i

# target to preprocess a source file
lib/JUCE/modules/juce_core/juce_core.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_core/juce_core.mm.i
.PHONY : lib/JUCE/modules/juce_core/juce_core.mm.i

lib/JUCE/modules/juce_core/juce_core.s: lib/JUCE/modules/juce_core/juce_core.mm.s
.PHONY : lib/JUCE/modules/juce_core/juce_core.s

# target to generate assembly for a file
lib/JUCE/modules/juce_core/juce_core.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_core/juce_core.mm.s
.PHONY : lib/JUCE/modules/juce_core/juce_core.mm.s

lib/JUCE/modules/juce_core/juce_core_CompilationTime.o: lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o
.PHONY : lib/JUCE/modules/juce_core/juce_core_CompilationTime.o

# target to build an object file
lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o
.PHONY : lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.o

lib/JUCE/modules/juce_core/juce_core_CompilationTime.i: lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : lib/JUCE/modules/juce_core/juce_core_CompilationTime.i

# target to preprocess a source file
lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i
.PHONY : lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.i

lib/JUCE/modules/juce_core/juce_core_CompilationTime.s: lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : lib/JUCE/modules/juce_core/juce_core_CompilationTime.s

# target to generate assembly for a file
lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s
.PHONY : lib/JUCE/modules/juce_core/juce_core_CompilationTime.cpp.s

lib/JUCE/modules/juce_data_structures/juce_data_structures.o: lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : lib/JUCE/modules/juce_data_structures/juce_data_structures.o

# target to build an object file
lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.o

lib/JUCE/modules/juce_data_structures/juce_data_structures.i: lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : lib/JUCE/modules/juce_data_structures/juce_data_structures.i

# target to preprocess a source file
lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.i

lib/JUCE/modules/juce_data_structures/juce_data_structures.s: lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : lib/JUCE/modules/juce_data_structures/juce_data_structures.s

# target to generate assembly for a file
lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : lib/JUCE/modules/juce_data_structures/juce_data_structures.mm.s

lib/JUCE/modules/juce_dsp/juce_dsp.o: lib/JUCE/modules/juce_dsp/juce_dsp.mm.o
.PHONY : lib/JUCE/modules/juce_dsp/juce_dsp.o

# target to build an object file
lib/JUCE/modules/juce_dsp/juce_dsp.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_dsp/juce_dsp.mm.o
.PHONY : lib/JUCE/modules/juce_dsp/juce_dsp.mm.o

lib/JUCE/modules/juce_dsp/juce_dsp.i: lib/JUCE/modules/juce_dsp/juce_dsp.mm.i
.PHONY : lib/JUCE/modules/juce_dsp/juce_dsp.i

# target to preprocess a source file
lib/JUCE/modules/juce_dsp/juce_dsp.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_dsp/juce_dsp.mm.i
.PHONY : lib/JUCE/modules/juce_dsp/juce_dsp.mm.i

lib/JUCE/modules/juce_dsp/juce_dsp.s: lib/JUCE/modules/juce_dsp/juce_dsp.mm.s
.PHONY : lib/JUCE/modules/juce_dsp/juce_dsp.s

# target to generate assembly for a file
lib/JUCE/modules/juce_dsp/juce_dsp.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_dsp/juce_dsp.mm.s
.PHONY : lib/JUCE/modules/juce_dsp/juce_dsp.mm.s

lib/JUCE/modules/juce_events/juce_events.o: lib/JUCE/modules/juce_events/juce_events.mm.o
.PHONY : lib/JUCE/modules/juce_events/juce_events.o

# target to build an object file
lib/JUCE/modules/juce_events/juce_events.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_events/juce_events.mm.o
.PHONY : lib/JUCE/modules/juce_events/juce_events.mm.o

lib/JUCE/modules/juce_events/juce_events.i: lib/JUCE/modules/juce_events/juce_events.mm.i
.PHONY : lib/JUCE/modules/juce_events/juce_events.i

# target to preprocess a source file
lib/JUCE/modules/juce_events/juce_events.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_events/juce_events.mm.i
.PHONY : lib/JUCE/modules/juce_events/juce_events.mm.i

lib/JUCE/modules/juce_events/juce_events.s: lib/JUCE/modules/juce_events/juce_events.mm.s
.PHONY : lib/JUCE/modules/juce_events/juce_events.s

# target to generate assembly for a file
lib/JUCE/modules/juce_events/juce_events.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_events/juce_events.mm.s
.PHONY : lib/JUCE/modules/juce_events/juce_events.mm.s

lib/JUCE/modules/juce_graphics/juce_graphics.o: lib/JUCE/modules/juce_graphics/juce_graphics.mm.o
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics.o

# target to build an object file
lib/JUCE/modules/juce_graphics/juce_graphics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics.mm.o
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics.mm.o

lib/JUCE/modules/juce_graphics/juce_graphics.i: lib/JUCE/modules/juce_graphics/juce_graphics.mm.i
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics.i

# target to preprocess a source file
lib/JUCE/modules/juce_graphics/juce_graphics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics.mm.i
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics.mm.i

lib/JUCE/modules/juce_graphics/juce_graphics.s: lib/JUCE/modules/juce_graphics/juce_graphics.mm.s
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics.s

# target to generate assembly for a file
lib/JUCE/modules/juce_graphics/juce_graphics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics.mm.s
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics.mm.s

lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o: lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o

# target to build an object file
lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.o

lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i: lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i

# target to preprocess a source file
lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.i

lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s: lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s

# target to generate assembly for a file
lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.cpp.s

lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o: lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o

# target to build an object file
lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.o

lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i: lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i

# target to preprocess a source file
lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.i

lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s: lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s

# target to generate assembly for a file
lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s
.PHONY : lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.c.s

lib/JUCE/modules/juce_gui_basics/juce_gui_basics.o: lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : lib/JUCE/modules/juce_gui_basics/juce_gui_basics.o

# target to build an object file
lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.o

lib/JUCE/modules/juce_gui_basics/juce_gui_basics.i: lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : lib/JUCE/modules/juce_gui_basics/juce_gui_basics.i

# target to preprocess a source file
lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.i

lib/JUCE/modules/juce_gui_basics/juce_gui_basics.s: lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : lib/JUCE/modules/juce_gui_basics/juce_gui_basics.s

# target to generate assembly for a file
lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : lib/JUCE/modules/juce_gui_basics/juce_gui_basics.mm.s

lib/JUCE/modules/juce_gui_extra/juce_gui_extra.o: lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : lib/JUCE/modules/juce_gui_extra/juce_gui_extra.o

# target to build an object file
lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.o

lib/JUCE/modules/juce_gui_extra/juce_gui_extra.i: lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : lib/JUCE/modules/juce_gui_extra/juce_gui_extra.i

# target to preprocess a source file
lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.i

lib/JUCE/modules/juce_gui_extra/juce_gui_extra.s: lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : lib/JUCE/modules/juce_gui_extra/juce_gui_extra.s

# target to generate assembly for a file
lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : lib/JUCE/modules/juce_gui_extra/juce_gui_extra.mm.s

src/PluginEditor.o: src/PluginEditor.cpp.o
.PHONY : src/PluginEditor.o

# target to build an object file
src/PluginEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/src/PluginEditor.cpp.o
.PHONY : src/PluginEditor.cpp.o

src/PluginEditor.i: src/PluginEditor.cpp.i
.PHONY : src/PluginEditor.i

# target to preprocess a source file
src/PluginEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/src/PluginEditor.cpp.i
.PHONY : src/PluginEditor.cpp.i

src/PluginEditor.s: src/PluginEditor.cpp.s
.PHONY : src/PluginEditor.s

# target to generate assembly for a file
src/PluginEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/src/PluginEditor.cpp.s
.PHONY : src/PluginEditor.cpp.s

src/PluginProcessor.o: src/PluginProcessor.cpp.o
.PHONY : src/PluginProcessor.o

# target to build an object file
src/PluginProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/src/PluginProcessor.cpp.o
.PHONY : src/PluginProcessor.cpp.o

src/PluginProcessor.i: src/PluginProcessor.cpp.i
.PHONY : src/PluginProcessor.i

# target to preprocess a source file
src/PluginProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/src/PluginProcessor.cpp.i
.PHONY : src/PluginProcessor.cpp.i

src/PluginProcessor.s: src/PluginProcessor.cpp.s
.PHONY : src/PluginProcessor.s

# target to generate assembly for a file
src/PluginProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NewProject.dir/build.make CMakeFiles/NewProject.dir/src/PluginProcessor.cpp.s
.PHONY : src/PluginProcessor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... NewProject_All"
	@echo "... NewProject"
	@echo "... NewProject_AU"
	@echo "... NewProject_Standalone"
	@echo "... NewProject_VST3"
	@echo "... Resources"
	@echo "... juce_vst3_helper"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData1.o"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData1.i"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData1.s"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData2.o"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData2.i"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData2.s"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData3.o"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData3.i"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData3.s"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData4.o"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData4.i"
	@echo "... juce_binarydata_Resources/JuceLibraryCode/BinaryData4.s"
	@echo "... lib/JUCE/modules/juce_audio_basics/juce_audio_basics.o"
	@echo "... lib/JUCE/modules/juce_audio_basics/juce_audio_basics.i"
	@echo "... lib/JUCE/modules/juce_audio_basics/juce_audio_basics.s"
	@echo "... lib/JUCE/modules/juce_audio_devices/juce_audio_devices.o"
	@echo "... lib/JUCE/modules/juce_audio_devices/juce_audio_devices.i"
	@echo "... lib/JUCE/modules/juce_audio_devices/juce_audio_devices.s"
	@echo "... lib/JUCE/modules/juce_audio_formats/juce_audio_formats.o"
	@echo "... lib/JUCE/modules/juce_audio_formats/juce_audio_formats.i"
	@echo "... lib/JUCE/modules/juce_audio_formats/juce_audio_formats.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3ManifestHelper.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AAX_utils.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_ARA.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_2.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_AUv3.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_LV2.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Unity.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.s"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.o"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.i"
	@echo "... lib/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.s"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors.o"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors.i"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors.s"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.o"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.i"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors_ara.s"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i"
	@echo "... lib/JUCE/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s"
	@echo "... lib/JUCE/modules/juce_audio_utils/juce_audio_utils.o"
	@echo "... lib/JUCE/modules/juce_audio_utils/juce_audio_utils.i"
	@echo "... lib/JUCE/modules/juce_audio_utils/juce_audio_utils.s"
	@echo "... lib/JUCE/modules/juce_core/juce_core.o"
	@echo "... lib/JUCE/modules/juce_core/juce_core.i"
	@echo "... lib/JUCE/modules/juce_core/juce_core.s"
	@echo "... lib/JUCE/modules/juce_core/juce_core_CompilationTime.o"
	@echo "... lib/JUCE/modules/juce_core/juce_core_CompilationTime.i"
	@echo "... lib/JUCE/modules/juce_core/juce_core_CompilationTime.s"
	@echo "... lib/JUCE/modules/juce_data_structures/juce_data_structures.o"
	@echo "... lib/JUCE/modules/juce_data_structures/juce_data_structures.i"
	@echo "... lib/JUCE/modules/juce_data_structures/juce_data_structures.s"
	@echo "... lib/JUCE/modules/juce_dsp/juce_dsp.o"
	@echo "... lib/JUCE/modules/juce_dsp/juce_dsp.i"
	@echo "... lib/JUCE/modules/juce_dsp/juce_dsp.s"
	@echo "... lib/JUCE/modules/juce_events/juce_events.o"
	@echo "... lib/JUCE/modules/juce_events/juce_events.i"
	@echo "... lib/JUCE/modules/juce_events/juce_events.s"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics.o"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics.i"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics.s"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.o"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.i"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics_Harfbuzz.s"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.o"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.i"
	@echo "... lib/JUCE/modules/juce_graphics/juce_graphics_Sheenbidi.s"
	@echo "... lib/JUCE/modules/juce_gui_basics/juce_gui_basics.o"
	@echo "... lib/JUCE/modules/juce_gui_basics/juce_gui_basics.i"
	@echo "... lib/JUCE/modules/juce_gui_basics/juce_gui_basics.s"
	@echo "... lib/JUCE/modules/juce_gui_extra/juce_gui_extra.o"
	@echo "... lib/JUCE/modules/juce_gui_extra/juce_gui_extra.i"
	@echo "... lib/JUCE/modules/juce_gui_extra/juce_gui_extra.s"
	@echo "... src/PluginEditor.o"
	@echo "... src/PluginEditor.i"
	@echo "... src/PluginEditor.s"
	@echo "... src/PluginProcessor.o"
	@echo "... src/PluginProcessor.i"
	@echo "... src/PluginProcessor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/BWRS1_dev/krump_vst/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

